services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_frontend
    restart: always
    ports:
      - "8081:80"
    networks:
      - global_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  global_net:
    external: true
    name: ticketing_global_net