server {
    listen 80;

    # 1. API: Todo lo que empiece con /api va a NestJS
    location /api/ {
        # Gracias a ticketing_global_net, nginx encuentra a nestjs_backend por su nombre
        proxy_pass http://nestjs_backend:3000;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. WEBSOCKETS: Todo lo que vaya a Socket.io va a NestJS
    location /socket.io/ {
        proxy_pass http://nestjs_backend:3000;
        
        # Estas cabeceras mantienen viva la conexión en tiempo real
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. STATIC ASSETS: Archivos de React optimizados
    location /assets/ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # 4. FRONTEND: El comodín que sirve tu app en React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}