server {
    listen 8001;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # CRUCIAL: Intenta servir el archivo, si no existe, sirve el index.html
        try_files $uri $uri/ /index.html;
    }

    # Optimización para archivos estáticos (JS, CSS, Imágenes)
    location /assets/ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}