import { AppRoles, type AppRoleType } from "@/auth/interfaces/authResponse.interface";
export const CONSUMABLES_PERMISSIONS = {
    CREATE_BATCH: 'CREATE_BATCH',
    CREATE_CONSUMABLE_OUTPUT: 'CREATE_CONSUMABLE_OUTPUT',
    CREATE_CONSUMABLE: 'CREATE_CONSUMABLE',
    EDIT_CONSUMABLE: 'EDIT_CONSUMABLE',
    ADD_CONSUMABLE_BAG: 'ADD_CONSUMABLE_BAG',
    MOV_ADD_CONSUMABLE_TO_THE_BAG: 'MOV_ADD_CONSUMABLE_TO_THE_BAG',
    VIEW_CONSUMABLES_CATALOG: 'VIEW_CONSUMABLES_CATALOG',
    VIEW_CONSUMABLE_DETAILS: 'VIEW_CONSUMABLE_DETAILS',
    VIEW_MOVEMENTS_HISTORY: 'VIEW_MOVEMENTS_HISTORY',
    VIEW_MOVEMENT_DETAILS: 'VIEW_MOVEMENT_DETAILS',
    //eQUIPMENTS
    CREATE_EQUIPMENT: 'CREATE_EQUIPMENT',
    VIEW_EQUIPMENTS_CATALOG: 'VIEW_EQUIPMENTS_CATALOG',
    VIEW_DETAILS_EQUIPMENT: 'VIEW_DETAILS_EQUIPMENT',
    EDIT_EQUIPMENT: 'EDIT_EQUIPMENT',
    MODIFICATION_STATUS: 'MODIFICATION_STATUS',
} as const;

export type ConsumablesPermissionsTypes = typeof CONSUMABLES_PERMISSIONS[keyof typeof CONSUMABLES_PERMISSIONS];
export const CONSUMABLES_ROLE_PERMISSIONS: Record<AppRoleType, Partial<ConsumablesPermissionsTypes[]>> = {
    [AppRoles.SuperAdmin]: [
        CONSUMABLES_PERMISSIONS.CREATE_BATCH,
        CONSUMABLES_PERMISSIONS.CREATE_CONSUMABLE_OUTPUT,
        CONSUMABLES_PERMISSIONS.CREATE_CONSUMABLE,
        CONSUMABLES_PERMISSIONS.EDIT_CONSUMABLE,
        CONSUMABLES_PERMISSIONS.ADD_CONSUMABLE_BAG,
        CONSUMABLES_PERMISSIONS.MOV_ADD_CONSUMABLE_TO_THE_BAG,
        CONSUMABLES_PERMISSIONS.VIEW_CONSUMABLES_CATALOG,
        CONSUMABLES_PERMISSIONS.VIEW_CONSUMABLE_DETAILS,
        CONSUMABLES_PERMISSIONS.VIEW_MOVEMENTS_HISTORY,
        CONSUMABLES_PERMISSIONS.VIEW_MOVEMENT_DETAILS,
        // ESTE ES EQUOIPMENTS
        CONSUMABLES_PERMISSIONS.VIEW_EQUIPMENTS_CATALOG,
        CONSUMABLES_PERMISSIONS.VIEW_DETAILS_EQUIPMENT,
        CONSUMABLES_PERMISSIONS.CREATE_EQUIPMENT,
        CONSUMABLES_PERMISSIONS.EDIT_EQUIPMENT,
        CONSUMABLES_PERMISSIONS.MODIFICATION_STATUS,
    ],
    [AppRoles.JefeCC]: [
        // CONSUMABLES_PERMISSIONS.CREATE_BATCH,
        // CONSUMABLES_PERMISSIONS.CREATE_CONSUMABLE_OUTPUT,
        // CONSUMABLES_PERMISSIONS.CREATE_CONSUMABLE,
        // CONSUMABLES_PERMISSIONS.EDIT_CONSUMABLE,
        // CONSUMABLES_PERMISSIONS.ADD_CONSUMABLE_BAG,
        // CONSUMABLES_PERMISSIONS.MOV_ADD_CONSUMABLE_TO_THE_BAG,
        CONSUMABLES_PERMISSIONS.VIEW_CONSUMABLES_CATALOG,
        CONSUMABLES_PERMISSIONS.VIEW_CONSUMABLE_DETAILS,
        CONSUMABLES_PERMISSIONS.VIEW_MOVEMENTS_HISTORY,
        CONSUMABLES_PERMISSIONS.VIEW_MOVEMENT_DETAILS,
        //equipos
        // CONSUMABLES_PERMISSIONS.CREATE_EQUIPMENT,
        // CONSUMABLES_PERMISSIONS.EDIT_EQUIPMENT,
        // CONSUMABLES_PERMISSIONS.MODIFICATION_STATUS
        CONSUMABLES_PERMISSIONS.VIEW_EQUIPMENTS_CATALOG,
        CONSUMABLES_PERMISSIONS.VIEW_DETAILS_EQUIPMENT,
    ],
    [AppRoles.Coordinador]: [
        // CONSUMABLES_PERMISSIONS.CREATE_BATCH,
        // CONSUMABLES_PERMISSIONS.CREATE_CONSUMABLE_OUTPUT,
        // CONSUMABLES_PERMISSIONS.CREATE_CONSUMABLE,
        // CONSUMABLES_PERMISSIONS.EDIT_CONSUMABLE,
        // CONSUMABLES_PERMISSIONS.ADD_CONSUMABLE_BAG,
        // CONSUMABLES_PERMISSIONS.MOV_ADD_CONSUMABLE_TO_THE_BAG,
        CONSUMABLES_PERMISSIONS.VIEW_CONSUMABLES_CATALOG,
        CONSUMABLES_PERMISSIONS.VIEW_CONSUMABLE_DETAILS,
        CONSUMABLES_PERMISSIONS.VIEW_MOVEMENTS_HISTORY,
        CONSUMABLES_PERMISSIONS.VIEW_MOVEMENT_DETAILS,
        //equipos
        // CONSUMABLES_PERMISSIONS.CREATE_EQUIPMENT,
        // CONSUMABLES_PERMISSIONS.EDIT_EQUIPMENT,
        // CONSUMABLES_PERMISSIONS.MODIFICATION_STATUS,
        CONSUMABLES_PERMISSIONS.VIEW_EQUIPMENTS_CATALOG,
        CONSUMABLES_PERMISSIONS.VIEW_DETAILS_EQUIPMENT,
    ],
    [AppRoles.Inventario]: [
        CONSUMABLES_PERMISSIONS.CREATE_BATCH,
        CONSUMABLES_PERMISSIONS.CREATE_CONSUMABLE_OUTPUT,
        CONSUMABLES_PERMISSIONS.CREATE_CONSUMABLE,
        CONSUMABLES_PERMISSIONS.EDIT_CONSUMABLE,
        CONSUMABLES_PERMISSIONS.ADD_CONSUMABLE_BAG,
        CONSUMABLES_PERMISSIONS.MOV_ADD_CONSUMABLE_TO_THE_BAG,
        CONSUMABLES_PERMISSIONS.VIEW_CONSUMABLES_CATALOG,
        CONSUMABLES_PERMISSIONS.VIEW_CONSUMABLE_DETAILS,
        CONSUMABLES_PERMISSIONS.VIEW_MOVEMENTS_HISTORY,
        CONSUMABLES_PERMISSIONS.VIEW_MOVEMENT_DETAILS,
    ],
    [AppRoles.JefeDepartamento]: [],
    [AppRoles.Planeacion]: [],
    [AppRoles.SecretariaCC]: [
        // CONSUMABLES_PERMISSIONS.CREATE_BATCH,
        // CONSUMABLES_PERMISSIONS.CREATE_CONSUMABLE_OUTPUT,
        // CONSUMABLES_PERMISSIONS.CREATE_CONSUMABLE,
        // CONSUMABLES_PERMISSIONS.EDIT_CONSUMABLE,
        // CONSUMABLES_PERMISSIONS.ADD_CONSUMABLE_BAG,
        // CONSUMABLES_PERMISSIONS.MOV_ADD_CONSUMABLE_TO_THE_BAG,
        CONSUMABLES_PERMISSIONS.VIEW_CONSUMABLES_CATALOG,
        CONSUMABLES_PERMISSIONS.VIEW_CONSUMABLE_DETAILS,
        CONSUMABLES_PERMISSIONS.VIEW_MOVEMENTS_HISTORY,
        CONSUMABLES_PERMISSIONS.VIEW_MOVEMENT_DETAILS,
        //equipos
        // CONSUMABLES_PERMISSIONS.CREATE_EQUIPMENT,
        // CONSUMABLES_PERMISSIONS.EDIT_EQUIPMENT,
        // CONSUMABLES_PERMISSIONS.MODIFICATION_STATUS
        CONSUMABLES_PERMISSIONS.VIEW_EQUIPMENTS_CATALOG,
        CONSUMABLES_PERMISSIONS.VIEW_DETAILS_EQUIPMENT,
    ],
    [AppRoles.Tecnico]: [
        //EQUIPMENS PERMISOS
        CONSUMABLES_PERMISSIONS.CREATE_EQUIPMENT,
        CONSUMABLES_PERMISSIONS.VIEW_EQUIPMENTS_CATALOG,
        CONSUMABLES_PERMISSIONS.VIEW_DETAILS_EQUIPMENT,
        CONSUMABLES_PERMISSIONS.EDIT_EQUIPMENT,
        CONSUMABLES_PERMISSIONS.MODIFICATION_STATUS
    ],
    [AppRoles.Visitante]: []
};